import Config

# Configure your database
config :app, App.Repo,
  url: System.get_env("DATABASE_URL") || "postgresql://postgres:changeme@db:5432/cie10_app",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :app, App.EventStore,
  serializer: App.JsonSerializer,
  url: System.get_env("EVENT_STORE_URL") || "postgresql://postgres:changeme@db:5432/cie10_eventstore"

# URL del microservicio de IA
config :app, :ai_engine_url, System.get_env("AI_ENGINE_URL") || "http://localhost:8000"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :app, AppWeb.Endpoint,
  # Binding to 0.0.0.0 to allow access from Docker network
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "iRIPjGUBVKcqO9aAVJb8x9skd/XdL4bgY13H/E7+0u++4n4UhQY6w/eArS/PbsoK",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :app, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Use Mailpit SMTP in development (docker-compose service on port 1025)
config :app, App.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: System.get_env("SMTP_HOST") || "localhost",
  port: String.to_integer(System.get_env("SMTP_PORT") || "1025"),
  tls: :never,
  auth: :never

config :swoosh, :api_client, Swoosh.ApiClient.Finch
config :swoosh, :finch_name, App.Finch
